name: Sync to Gitee

on:
  push:
    branches: [ main ]

jobs:
  sync-code:
    name: Sync Code to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}
        run: |
          git remote add gitee "https://yeliqin666:${GITEE_TOKEN}@gitee.com/yeliqin666/xjtu-toolbox-android.git"
          git push gitee main:main --force